
# Camera
CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 20
CAMERA_FRAME_SKIP = 1  

# Tracking
YOLO_MODEL = "yolov8n.pt"
ONLY_PERSON = False          
PERSONS_CAT_DOG=True
SHOW_YOLO_LABELS = True
CONFIDENCE_THRESHOLD = 0.45
TRACKER_CONFIG = "bytetrack.yaml"   
TRACK_PERSIST = True

# Recognition
KNOWN_FACES_DIR = "known_faces"
FACE_DET_SIZE = (640,640)
FACE_SIM_THRESHOLD = 0.30
FACE_SCAN_EVERY_N_FRAMES = 5
TRACK_NAME_TTL_FRAMES = 60

# Selection
FACE_MIN_PERSON_CONF = 0.6
FACE_PROCESS_TOP_N = 2
FACE_SIM_THRESHOLD_HIGH = 0.50  
FACE_SIM_THRESHOLD_LOW = 0.35   

# Batch Processing
FACE_BATCH_SIZE = 5
FACE_DET_SIZE_FAST = (320, 320) 
FACE_QUALITY_MIN_SIZE = (80, 80)            

#Other
PETS=True



UNKNOWN_EVENT_MIN_SECONDS = 20.0
KNOWN_PERSON_COOLDOWN_SECONDS = 60.0

CLOUD_API_BASE_URL = "http://192.168.1.148:9000"
CLOUD_SYSTEM_ID = 1